name: Install SteamCMD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-steamcmd:
    runs-on: ubuntu-latest

    steps:
    - name: Install steamcmd
      run: mkdir -p /tmp/SteamCMD && curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxf - -C /tmp/SteamCMD

    - name: Install Project Zomboid Dedicated Server
      run: /tmp/SteamCMD/steamcmd.sh -flushlog +force_install_dir /tmp/pz-rm-explorer +login anonymous +app_update 380870 validate +quit

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        go-version: '1.20'
        
    - name: Build Go project
      run: |
        go mod tidy
        go build -v ./...

    - name: Run Go project
      run: ./main
